name: Run HelloWorld.java

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # 手動実行も可能にする

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v3

      - name: Java をインストール
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # または必要なバージョン

      - name: HelloWorld.java をコンパイル
        run: javac HelloWorld.java

      - name: HelloWorld を実行
        run: java HelloWorld
